config/routes.rb
Rails.application.routes.draw do
  root 'my_first_page#index'
  resources :goods

end

app/models/good.rb
class Good < ActiveRecord::Base
  has_many :goods_providers, dependent: :destroy
  has_many :providers, through: :goods_providers
end

app/models/goods_provider.rb
class GoodsProvider < ActiveRecord::Base
  belongs_to :goods
  belongs_to :providers
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  has_many :goods_providers, dependent: :destroy
  has_many :goods, through: :goods_providers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController

  def new
    @good = Good.new
  end

  def index
    @goods_count = Good.count
    @goods = Good.all
  end

  def show
  @good = Good.find(params[:id])
  end


  def create

    @good = Good.new
    @good.code = params[:good][:code]
    @good.name = params[:good][:name]
    @good.save

    redirect_to goods_path

  end

  def edit
  @good = Good.find(params[:id])
  end

  def update
    @good = Good.find(params[:id])
    @good.code = params[:good][:code]
    @good.name = params[:good][:name]
    @good.save

    redirect_to goods_path
  end

  def destroy
    Good.find(params[:id]).destroy
    redirect_to  goods_path
  end
end

app/controllers/my_first_page_controller.rb
class MyFirstPageController < ApplicationController

  def index

  end

  def create

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/my_first_page_helper.rb
module MyFirstPageHelper
end

app/views/goods/_form.html.erb
<%= form_for @good do |form| %>
    <%= form.label :code,'Код' %>
    <%= form.text_field :code %>
    <%= form.label :name,'Название' %>
    <%= form.text_field :name %>

    <%= form.submit 'Сохранить' %>

<% end %>

app/views/goods/edit.html.erb
<%= render partial: 'form' %>

app/views/goods/index.html.erb
<h1>Товары</h1>

<p>Товаров на складе <%= @goods_count %></p>

<table>
  <% @goods.each do |good| %>
  <tr>
    <td><%= good.code %></td>
    <td><%= link_to(good.name, good_path(id: good.id)) %></td>
    <td><%= link_to('Edit', edit_good_path(id: good.id)) %></td>

    <td><%= link_to('Delete', good_path(id: good.id), method: :delete) %></td>
  </tr>

  <% end %>
</table>
<br>
<%= link_to('Добавить товар', new_good_path) %>

app/views/goods/new.html.erb
<%= render partial: 'form' %>

app/views/goods/show.html.erb
<h1><%= @good.name %></h1>

<ul>
  <li><%= @good.code %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/my_first_page/index.html.erb
<h1 id="hello_world">Hello World</h1>



<p>Link 1</p>
<p>Link 2</p>
<p>Link 3</p>
<p class="subgroup">Link 4</p>
<p class="subgroup">Link 5</p>